// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'null',
    appId: '1:578234897962:web:7844ba2700dba72b0dd553',
    messagingSenderId: '578234897962',
    projectId: 'homely-project-8be33',
    authDomain: 'homely-project-8be33.firebaseapp.com',
    databaseURL: 'https://homely-project-8be33-default-rtdb.firebaseio.com',
    storageBucket: 'homely-project-8be33.appspot.com',
    measurementId: 'G-HLPFSD934T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'null',
    appId: '1:578234897962:android:76e3504d38df8faa0dd553',
    messagingSenderId: '578234897962',
    projectId: 'homely-project-8be33',
    databaseURL: 'https://homely-project-8be33-default-rtdb.firebaseio.com',
    storageBucket: 'homely-project-8be33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'null',
    appId: '1:578234897962:ios:1efe11259dec758e0dd553',
    messagingSenderId: '578234897962',
    projectId: 'homely-project-8be33',
    databaseURL: 'https://homely-project-8be33-default-rtdb.firebaseio.com',
    storageBucket: 'homely-project-8be33.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
